### ISSUE TITLE
Nenhum pop-up de endereço é exibido ao clicar na localização atual do usuário.

### ISSUE THREAD

**Issue by LiviaBorges** [Connect-Eco/connecteco#33]
Passos para reprodução:
    1- Acessar o site Connect Eco
    2- A localização atual é exibida no cabeçalho
    3- Clicar na localização atual
    4- O pop-up de endereço deve ser exibido

Resultado esperado: Ao clicar na localização atual do usuario, o pop-up de endereço é exibido na tela.

Resultado Real: Ao clicar na localização atual, o botão mostra um simbolo de carregando mas nenhum pop-up de endereço é exibido.

Ambiente: Google Chrome Versão 125.0.6422.141 
Resolução: 1920x1080

![bug1](https://github.com/Connect-Eco/connecteco/assets/111646772/85f5c47b-d043-410b-8dd8-3769c4121d01)

**Comment by FelipeM-F** [comment]
Não foi possível implementar essa funcionalidade na versão atual do site, ficará para as próximas.

**Comment by FelipeM-F** [comment]
Não foi possível implementar essa funcionalidade na versão atual do site, ficará para as próximas.

**Comment by FelipeM-F** [comment]
Fechado
